### ISSUE TITLE
Better GUI Package?

### ISSUE THREAD

**Issue by mattdreimer** [mattdreimer/AutonomousGrainCart#7]
Maybe we should be looking at a complete redesign of the GUI.  I used pygame only because I was somewhat familiar with it and I was in a hurry but it has some issues in my opinion, maybe we should be using tkinter or something else.  I've used Kivy once to write an app in python for my phone.  Kivy has some advantages in that it is designed for touch and has all the builtin features to resize the screen and buttons and so on.

**Comment by mattdreimer** [comment]
now using Tkinter and ttk widgets

**Comment by fanquake** [comment]
Cool. Look forward to testing this.
